export const subSections1 = [
    {title: "arts",
      id: 0},
    {title: "books",
      id: 1},
    {title: "business",
      id: 2},
    {title: "fashion",
      id: 3},
    {title: "food",
      id: 4},
    {title: "health",
      id: 5},
    {title: "magazine",
      id: 6},
    
  ];
export const subSections2 = [
  {title: "movies",
    id: 7},
  {title: "politics",
    id: 8},
  {title: "science",
    id: 9},
  {title: "sports",
    id: 10},
  {title: "technology",
    id: 11},
  {title: "theater",
    id: 12},
  ];